AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - spec/spec_helper.rb

Gemspec/RequiredRubyVersion:
  Enabled: false
Gemspec/RequireMFA:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/cocoapods-xcconfig-hooks.rb

Style/StringLiterals:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Metrics/MethodLength:
  Enabled: false
Style/Documentation:
  Enabled: false
