name: Lint
on:
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install
        uses: trinhngocthuyen/gh-actions/rb/install@main
        with:
          bundle-install: true
      - name: Makefile
        uses: trinhngocthuyen/gh-actions/core/makefile@main
        with:
          targets: lint
